{
  "name": "Test",
  "on": {
    "workflow_dispatch": {},
    "pull_request": {
      "branches": [
        "main",
        "develop-*"
      ],
      "types": [
        "opened",
        "edited",
        "reopened",
        "ready_for_review",
        "synchronize"
      ]
    }
  },
  "env": {
    "CARGO_TERM_COLOR": "always"
  },
  "jobs": {
    "msrv": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"
        },
        {
          "name": "Install Rust 1.83",
          "uses": "dtolnay/rust-toolchain@bd41891a8e7f4b8649f6d684415e1a6155fe4e22",
          "with": {
            "toolchain": "1.83.0"
          }
        },
        {
          "name": "rustc",
          "run": "rustc --version"
        },
        {
          "name": "cargo",
          "run": "cargo --version"
        },
        {
          "name": "Update dependencies",
          "run": "cargo +stable update --config 'resolver.incompatible-rust-versions=\"fallback\"'"
        },
        {
          "name": "Check MSRV with arrow-53",
          "run": "cargo +1.83.0 check --package serde_arrow --features arrow-53"
        }
      ]
    },
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"
        },
        {
          "name": "Install uv",
          "uses": "astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39",
          "with": {
            "enable-cache": true
          }
        },
        {
          "name": "rustc",
          "run": "rustc --version"
        },
        {
          "name": "cargo",
          "run": "cargo --version"
        },
        {
          "name": "Check",
          "run": "cargo check"
        },
        {
          "name": "Check marrow serde",
          "run": "cargo check --package marrow --features serde"
        },
        {
          "name": "Check marrow arrow2-0-17",
          "run": "cargo check --package marrow --features arrow2-0-17"
        },
        {
          "name": "Check marrow arrow2-0-16",
          "run": "cargo check --package marrow --features arrow2-0-16"
        },
        {
          "name": "Check marrow arrow-59",
          "run": "cargo check --package marrow --features arrow-59"
        },
        {
          "name": "Check marrow arrow-58",
          "run": "cargo check --package marrow --features arrow-58"
        },
        {
          "name": "Check marrow arrow-57",
          "run": "cargo check --package marrow --features arrow-57"
        },
        {
          "name": "Check marrow arrow-56",
          "run": "cargo check --package marrow --features arrow-56"
        },
        {
          "name": "Check marrow arrow-55",
          "run": "cargo check --package marrow --features arrow-55"
        },
        {
          "name": "Check marrow arrow-54",
          "run": "cargo check --package marrow --features arrow-54"
        },
        {
          "name": "Check marrow arrow-53",
          "run": "cargo check --package marrow --features arrow-53"
        },
        {
          "name": "Check marrow arrow-52",
          "run": "cargo check --package marrow --features arrow-52"
        },
        {
          "name": "Check marrow arrow-51",
          "run": "cargo check --package marrow --features arrow-51"
        },
        {
          "name": "Check marrow arrow-50",
          "run": "cargo check --package marrow --features arrow-50"
        },
        {
          "name": "Check marrow arrow-49",
          "run": "cargo check --package marrow --features arrow-49"
        },
        {
          "name": "Check marrow arrow-48",
          "run": "cargo check --package marrow --features arrow-48"
        },
        {
          "name": "Check marrow arrow-47",
          "run": "cargo check --package marrow --features arrow-47"
        },
        {
          "name": "Check marrow arrow-46",
          "run": "cargo check --package marrow --features arrow-46"
        },
        {
          "name": "Check marrow arrow-45",
          "run": "cargo check --package marrow --features arrow-45"
        },
        {
          "name": "Check marrow arrow-44",
          "run": "cargo check --package marrow --features arrow-44"
        },
        {
          "name": "Check marrow arrow-43",
          "run": "cargo check --package marrow --features arrow-43"
        },
        {
          "name": "Check marrow arrow-42",
          "run": "cargo check --package marrow --features arrow-42"
        },
        {
          "name": "Check marrow arrow-41",
          "run": "cargo check --package marrow --features arrow-41"
        },
        {
          "name": "Check marrow arrow-40",
          "run": "cargo check --package marrow --features arrow-40"
        },
        {
          "name": "Check marrow arrow-39",
          "run": "cargo check --package marrow --features arrow-39"
        },
        {
          "name": "Check marrow arrow-38",
          "run": "cargo check --package marrow --features arrow-38"
        },
        {
          "name": "Check marrow arrow-37",
          "run": "cargo check --package marrow --features arrow-37"
        },
        {
          "name": "Check serde_arrow arrow-59",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-59"
        },
        {
          "name": "Check serde_arrow arrow-58",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-58"
        },
        {
          "name": "Check serde_arrow arrow-57",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-57"
        },
        {
          "name": "Check serde_arrow arrow-56",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-56"
        },
        {
          "name": "Check serde_arrow arrow-55",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-55"
        },
        {
          "name": "Check serde_arrow arrow-54",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-54"
        },
        {
          "name": "Check serde_arrow arrow-53",
          "run": "cargo check --all-targets --package serde_arrow --features arrow-53"
        },
        {
          "name": "Check support packages",
          "run": "cargo check --all-features --package serde_arrow_bench --package serde_arrow_example --package serde_arrow_integration --package marrow_integration"
        },
        {
          "name": "Check format",
          "run": "cargo fmt --check"
        },
        {
          "name": "Build",
          "run": "cargo build --package serde_arrow --package marrow --features serde_arrow/arrow-59,marrow/serde,marrow/arrow2-0-17,marrow/arrow-59"
        },
        {
          "name": "Test",
          "run": "cargo test --package serde_arrow --package marrow --features serde_arrow/arrow-59,marrow/serde,marrow/arrow2-0-17,marrow/arrow-59"
        },
        {
          "name": "Integration test",
          "run": "uv run python x.py test-integration"
        }
      ]
    }
  }
}